# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chat Application' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chat Application

  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'GoogleSignIn'
  pod 'ObjectMapper', '~> 2.2'
  pod 'Kingfisher', '~> 3.0'


end
