# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MagicChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MagicChat

	pod 'Firebase/Core'
	pod 'SwiftLint'
	pod 'Firebase/Database'
	pod 'Firebase/Auth'
	pod 'Firebase/Storage'
    pod 'BulletinBoard'
    pod 'Swinject'
    pod 'SwinjectStoryboard'

end
